title: Stephen Pearse — Audio • AI • Engineering
author: Stephen Pearse
email: pearse.audio@gmail.com
theme: minima
description: Selected projects in audio software, AI, and full-stack development.
markdown: kramdown

